### PR TITLE
Outside term

### PR DESCRIPTION
**Pull request by hurae**
preconfigred vim ide for python and go, also able to be recomplied with scripts easily with other language support

### CODE REVIEW

**Comment by hurae** [comment]
forget about link problem with compiled version of vim, sorry

**Comment by Escapingbug** [comment]
Actually this is by intention left for no such a thing as vim to be put into this docker to keep the container small. This is exactly why I'm working on outside terminal so that we don't need a terminal inside to enlarge the whole container.

The work flow that I personally recommend is to write something outside, use the `/pwn` shared directory to put it in, and debug inside the container.

**Comment by hurae** [comment]
I agree.

After put it everything for a great vim in, it's 1.96 GB with 16.04 and 2.16GB with 18.04.

But I use it because I'd like to use Windows 10 as my host system and use boot2docker in Virtualbox as docker's host system. So I do not have a nice environment for the container. I use WSL to provide the remote docker connection, Atom in windows to write code, WinSCP or rsync to transfer file. It seems an ugly things but it works and works well. It only cost 74 MB of memory or so. A larger image didn't bother me that much. After all, I don't download it every time. Don't build it every time either.

By the way, vim's link problem is easy to fix. I already fixed it.

**Comment by hurae** [comment]
well, virtualbox's share folder is a nice solution. I forgot that before.

**Pull request closed without merging**
